# Generated by Django 2.2 on 2019-07-18 13:24

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('md5', models.CharField(db_index=True, max_length=64)),
                ('accessed_count', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('file_type', models.IntegerField(choices=[(1, 'pssm'), (2, 'mtx')], default=2)),
                ('blast_hit_count', models.IntegerField(default=0)),
                ('runtime', models.IntegerField(default=0)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('sequence', models.CharField(db_index=True, max_length=65536)),
            ],
            options={
                'ordering': ('created',),
                'get_latest_by': 'created',
            },
        ),
    ]
