# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:59
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blast_cache_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='cache_entry',
        ),
        migrations.AlterModelOptions(
            name='cache_entry',
            options={'get_latest_by': 'created'},
        ),
        migrations.RemoveField(
            model_name='cache_entry',
            name='track_string',
        ),
        migrations.RemoveField(
            model_name='cache_entry',
            name='uniprotID',
        ),
        migrations.AddField(
            model_name='cache_entry',
            name='accessed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cache_entry',
            name='blast_hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cache_entry',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
        migrations.AddField(
            model_name='cache_entry',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 15, 59, 30, 902451, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cache_entry',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'pssm'), (2, 'chk')], default=2),
        ),
        migrations.AddField(
            model_name='cache_entry',
            name='protein_name',
            field=models.CharField(db_index=True, default='test', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cache_entry',
            name='runtime',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cache_entry',
            name='md5',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
