# Generated by Django 2.2 on 2019-10-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_cache_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache_entry',
            name='sequence',
            field=models.CharField(max_length=65536),
        ),
    ]
