# Generated by Django 2.2 on 2019-04-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_cache_app', '0013_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache_entry',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
