# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blast_cache_app', '0002_auto_20170516_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cache_entry',
            old_name='protein_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cache_entry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cache_entry',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
