# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_cache_app', '0003_auto_20170517_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cache_entry',
            options={'get_latest_by': 'created', 'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='cache_entry',
            old_name='blast_hits',
            new_name='blast_hit_count',
        ),
        migrations.AlterField(
            model_name='cache_entry',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
