# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_cache_app', '0004_auto_20170517_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache_entry',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
    ]
