# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_cache_app', '0005_auto_20170517_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache_entry',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
