# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_cache_app', '0006_auto_20170518_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache_entry',
            name='unique_hash',
            field=models.CharField(db_index=True, default='AAAAAAAAAAAAAAAAAAAAAA', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
