# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blast_cache_app', '0008_auto_20171026_1454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cache_entry',
            unique_together=set([('md5', 'settings_hash')]),
        ),
    ]
