# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_cache_app', '0009_auto_20171026_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache_entry',
            name='settings_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
