# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-04 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blast_cache_app', '0013_auto_20181113_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache_entry',
            name='blocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cache_entry',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'pssm'), (2, 'mtx')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='cache_entry',
            name='name',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cache_entry',
            name='sequence',
            field=models.CharField(db_index=True, max_length=65536, null=True),
        ),
    ]
